### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by ramisahoori** [HumbleNet/HumbleNet#18]
Hello.
I'm trying to build HumbleNet on windows . I'm using a Windows 10 x64 bit machine.
I tried to follow the instructions included on the home page but I end up with the following errors in step 4(when run the "cmake .." command inside the build directory) here is the cmake log:

-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.15.26726.0
-- The CXX compiler identification is MSVC 19.15.26726.0
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Looking for clock_gettime
-- Looking for clock_gettime - not found
-- Looking for dlopen
-- Looking for dlopen - not found
-- Performing Test CHECK_CXX_FLAG__Wno_deprecated_register
-- Performing Test CHECK_CXX_FLAG__Wno_deprecated_register - Failed
-- Performing Test CHECK_CXX_FLAG__Wno_int_to_void_pointer_cast
-- Performing Test CHECK_CXX_FLAG__Wno_int_to_void_pointer_cast - Failed
-- Configuring done
-- Generating done
-- Build files have been written to: D:/RTCDirectpry/HumbleNet-master/build

I can't find the file "humblepeer_generated.h" mentioned in the next step.
any help what I'm missing??
Best Regards

**Comment by hpcorona** [comment]
The readme file says that you first need to build flatbuffers on step 3, and then copy the include files.

Hope this helps!

**Comment by urkle** [comment]
Please check out the develop-1.1.x branch I also have a PR that will land there soon that will switch to a submodule for flatbuffers so that it no longer is an external dependency.
