### ISSUE TITLE
Is this library abandoned?

### ISSUE THREAD

**Issue by ghost** [HumbleNet/HumbleNet#21]
[The blog post](https://hacks.mozilla.org/2017/06/introducing-humblenet-a-cross-platform-networking-library-that-works-in-the-browser/) mentioned:

> We have a roadmap of what we plan on adding now that the project is released. Keep an eye on the HumbleNet site for the latest development.
>
> Future work items include:
>
>   1. Event API
     Allows a simple SDL2-style polling event system so that game code can easily check for various events from the peer server in a cleaner way, such as connects, disconnects, etc.
>   2. Lobby API
     Uses the Event API to build a means of creating lobbies on the peer server in order to locate game sessions (instead of having to register aliases).
>   3. WebSocket API
     Adds in support to easily connect to any websocket server with a clean simple API.

Would be cool to see them one day! :)

**Comment by ClientIco** [comment]
I am also curious ?

**Comment by caniko2** [comment]
Seems they didn't get enough money

**Comment by caniko** [comment]
Not dead, just neglected by the community

You are welcome to contribute:
https://github.com/HumbleNet/humblenet/blob/master/TODO.md

**Comment by ghost** [comment]
@caniko2 Community your way out of this issue.

**Comment by caniko** [comment]
> @caniko2 Community your way out of this issue.

What do you mean by "dead" anyway? It is not like the code is useless unless it is being developed.

**Comment by urkle** [comment]
FYI.. I am semi-actively working on HumbleNet. (have been for the past 2 months).

Right now I am working on an UE4 plugin for HumbleNet and have some funding going into development to start implementing some of the missing features (mainly lobbies)

**Comment by urkle** [comment]
I'm closing this issue now as I am more actively working on improving humblenet (see develop-1.1.x branch)
