### ISSUE TITLE
Automatic add FlatBuffers via CMake

### ISSUE THREAD

**Issue by pinguin999** [HumbleNet/HumbleNet#29]
Docs how to use FlatBuffers with Cmake https://google.github.io/flatbuffers/flatbuffers_guide_building.html

The FlatBuffers Repo can also be added as a git submodule let cmake pull it like:

```
	FetchContent_Declare(boost
		URL https://boostorg.jfrog.io/artifactory/main/release/1.71.0/source/boost_1_71_0.7z
		URL_HASH SHA256=1b3949ffddf56129141032542523920034f2e69775fb9332a52ba37c548dbf35)
	FetchContent_MakeAvailable(boost)
	FetchContent_GetProperties(boost SOURCE_DIR BOOST_SRC_DIR)
```

**Comment by urkle** [comment]
I think one option I would rather do is simply have it so I can "make a release" that has the headers pre-built in that mode so the build does not depend on flatc at all.

Though doing flatbuffers as an optional pull off the specific version we are using would be good too as they do break compatibility sometimes with newer versions. (on the code not on the flatbuffer protocol)

**Comment by urkle** [comment]
PR #30 switches to a submodule for flatbuffers
