### ISSUE TITLE
libwebsockets/lib/output.c:112: lws_issue_raw: Assertion `0' failed.

### ISSUE THREAD

**Issue by selvakn** [HumbleNet/HumbleNet#7]
OS: Ubuntu
Arch: x86_64

`./humblenet_test_peer.bin.x86_64` fails to connect to peer with the following error message

```
[1501043017:0562] ERR: ****** 22550e0 Sending new, pending truncated ...
humblenet_test_peer.bin.x86_64: /home/urkle/Projects/HumbleNet/humblenet/3rdparty/libwebsockets/lib/output.c:112: lws_issue_raw: Assertion `0' failed.
Aborted (core dumped)
```

**Comment by urkle** [comment]
A more complete backtrace might help here.. Though I do need to update the included libwebsockets at some point which may help this.

**Comment by urkle** [comment]
Closing due to not enough details
